import { afterEach, expect, it, vi } from 'vitest'
import { act, cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import '@testing-library/jest-dom/vitest'
const { send } = vi.hoisted(() => ({ send: vi.fn().mockResolvedValue({}) }))
vi.mock('next/navigation', () => ({ useRouter: () => ({ refresh: vi.fn() }) }))
vi.mock('@/lib/api/client', () => ({ apiSend: send, errorMessage: (error: Error) => error.message }))
vi.mock('@/components/shared/toast/ToastProvider', () => ({ useToast: () => ({ success: vi.fn(), error: vi.fn() }) }))
import VariantsTab, { type Variant } from '@/components/admin/VariantsTab'
afterEach(() => { cleanup(); vi.useRealTimers(); vi.clearAllMocks(); vi.unstubAllGlobals() })
const row: Variant = { id: 'print', product_id: 'art', name: 'Medium', medium: 'canvas', size_label: '16x20', width_in: 16, height_in: 20, is_custom_size: false, size_tier: 'M', lumaprints_cost_cents: 2000, shipping_cost_cents: 500, margin_override_pct: null, manual_price_override_cents: null, is_active: false, is_lumaprints_available: true, last_priced_at: null }
function show(variants = [row]) {
  render(<VariantsTab productId="art" productDefaultMargin={100} variants={variants} mediumCatalog={[{ medium: 'canvas', name: 'Canvas', subcategory_id: 101002, option_ids: [2], sizes: [], enabled: true, last_synced_at: null }]} master={{ width_px: 6400, height_px: 8000, print_width_px: 6400, print_height_px: 8000, print_status: 'ready', border_mode: 'full_bleed' }} />)
}
it('converts a row gross margin to saved markup, rejects 100% gross margin, and preserves zero/inheritance', async () => {
  vi.useFakeTimers()
  show()
  fireEvent.change(screen.getByLabelText('Medium Gross margin (%)'), { target: { value: '60' } })
  expect(screen.getByLabelText('Medium Markup (%)')).toHaveValue('150')
  await act(async () => { vi.advanceTimersByTime(550) })
  expect(send).toHaveBeenLastCalledWith('/api/admin/variants/print', 'PATCH', { margin_override_pct: 150 })
  send.mockClear()
  fireEvent.change(screen.getByLabelText('Medium Gross margin (%)'), { target: { value: '100' } })
  await act(async () => { vi.advanceTimersByTime(550) })
  expect(send).not.toHaveBeenCalled()
  fireEvent.change(screen.getByLabelText('Medium Markup (%)'), { target: { value: '0' } })
  await act(async () => { vi.advanceTimersByTime(550) })
  expect(send).toHaveBeenLastCalledWith('/api/admin/variants/print', 'PATCH', { margin_override_pct: 0 })
  fireEvent.change(screen.getByLabelText('Medium Markup (%)'), { target: { value: '' } })
  await act(async () => { vi.advanceTimersByTime(550) })
  expect(send).toHaveBeenLastCalledWith('/api/admin/variants/print', 'PATCH', { margin_override_pct: null })
})
it('shows the actual manual-price relationship as read-only and does not save on mount', () => {
  show([{ ...row, margin_override_pct: 200, manual_price_override_cents: 4000 }])
  expect(screen.getByLabelText('Medium Markup (%)')).toHaveValue('60')
  expect(screen.getByLabelText('Medium Gross margin (%)')).toHaveValue('37.5')
  expect(screen.getByLabelText('Medium Gross margin (%)')).toHaveAttribute('readonly')
  expect(screen.getByText('Manual price is fixed. Clear its price override to edit percentages.')).toBeInTheDocument()
  expect(send).not.toHaveBeenCalled()
})
it('does not treat a missing print cost as zero profit cost for a manual price', () => {
  show([{ ...row, lumaprints_cost_cents: null, manual_price_override_cents: 4000 }])
  expect(screen.getByText('Set costs to calculate markup and gross margin.')).toBeInTheDocument()
  expect(screen.queryByLabelText('Medium Markup (%)')).not.toBeInTheDocument()
  expect(within(screen.getAllByRole('row')[1]).getAllByRole('cell')[6]).toHaveTextContent('—')
  expect(screen.queryByText(/\$35.00 gross profit/)).not.toBeInTheDocument()
  expect(send).not.toHaveBeenCalled()
})
it('blocks invalid add-size gross margin but lets a valid manual price bypass the unused draft', async () => {
  vi.useFakeTimers()
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue(Response.json({ data: { cost_cents: 2000, shipping_cents: 500, price_cents: 5000 } })))
  show([])
  fireEvent.click(screen.getByRole('button', { name: '+ Add print size' }))
  await act(async () => { vi.advanceTimersByTime(400) })
  fireEvent.change(screen.getByLabelText('Print size Gross margin (%)'), { target: { value: '100' } })
  expect(screen.getByRole('button', { name: 'Save as Draft' })).toBeDisabled()
  fireEvent.click(screen.getByLabelText('Manual price'))
  fireEvent.change(screen.getByLabelText('Manual price ($)'), { target: { value: '40' } })
  expect(screen.getByLabelText('Print size Markup (%)')).toHaveValue('60')
  expect(screen.getByLabelText('Print size Gross margin (%)')).toHaveValue('37.5')
  expect(screen.getByRole('button', { name: 'Save as Draft' })).toBeEnabled()
  fireEvent.click(screen.getByRole('button', { name: 'Save as Draft' }))
  await act(async () => {})
  expect(send).toHaveBeenCalledWith('/api/admin/products/art/variants/custom', 'POST', expect.objectContaining({ margin_override_pct: null, manual_price_override_cents: 4000, width_in: 16, height_in: 20 }))
})
