export interface HelpArticle {
  slug: string
  title: string
  group: string
  summary: string
  screen: string
  screenAlt: string
  tool: { label: string; href: string }
  relatedTools?: { label: string; href: string }[]
  before: string
  steps: string[]
  example: string[]
  check: string[]
  troubleshoot: string
  extra?: { title: string; paragraphs: string[] }[]
  sources?: { label: string; href: string }[]
}

export const helpArticles: HelpArticle[] = [
  {
    slug: '01-start-here', title: 'Start here: your path to opening the shop', group: '1. Set your foundation',
    summary: 'Learn where things live and follow a clear setup order, one small job at a time.',
    screen: 'dashboard.png', screenAlt: 'Example main dashboard with sample orders, fulfillment controls, and sales reporting. Your live totals will differ.',
    tool: { label: 'Open your dashboard', href: '/admin' },
    relatedTools: [{ label: 'Open homepage designs', href: '/admin/pages/design-assets#homepages' }, { label: 'Open funnel designs', href: '/admin/pages/design-assets#funnels' }, { label: 'Review Features built', href: '/admin/settings#features-built' }],
    before: 'Sign in with your admin account. Keep this guide in one tab and your shop in another. Have one artwork photo, its size, and a starting price ready. You can begin with one product.',
    steps: [
      'Start on Dashboard. It brings your sales totals, sales tax tracker, fulfillment settings, and quick links together. Find the communication area near the bottom. Products holds the things you sell; Orders holds purchases; Pages changes website content; Media holds pictures; Settings holds business controls; Help & Guides brings you back here.',
      'Fill in your business details first. A buyer needs to know who you are and how to reach you. Read article 2, then save the business information in Settings.',
      'Choose who makes and ships prints. Read article 3 before changing Use Lumaprints. Your own studio and Lumaprints have separate saved prices, so the choice affects what buyers can buy.',
      'Build one complete product. Add a clear title, useful description, pictures, price, and the sizes you can deliver. Keep its status Draft until you check it. Articles 4 through 8 walk through this.',
      'Check the money. Learn margins in articles 9 and 10. Choose shipping in article 11. Set up sales tax in articles 12 and 13 before taking taxable orders.',
      'Read your site like a new customer. Fix unclear words, open the product, choose a size, and check the cart. Use article 17 as your final shop check. Then use articles 18 through 20 for daily work.',
    ],
    extra: [{ title: 'Know where the creative tools moved', paragraphs: ['Open Pages → Design Assets to review homepage and funnel designs. Homepage designs and Sales funnels are separate sections on that page. The regular Pages editor still changes the words and images on your existing website pages.', 'Open Settings and expand Features built when you want to review the feature list. It stays collapsed until you need it. Use the communication area near the bottom of Dashboard for project messages and notes; the main dashboard space is for running the shop.'] }],
    example: ['Think of the shop like an art fair table. Business details are your sign. Products are the art on the table. Prices are the price tags. Fulfillment is how the art gets home. Orders are your receipt book.'],
    check: ['You can find Products, Orders, Pages, Media, Settings, and Help.', 'You have a short list of unfinished setup jobs and one product to finish first.'],
    troubleshoot: 'If a screen asks you to sign in again, sign in and return to the same tool. If an admin tool is missing, make sure you are using an account with admin access. Do not make a second product just because the first page is slow.',
  },
  {
    slug: '02-business-details', title: 'Add your business name and contact details', group: '1. Set your foundation',
    summary: 'Give customers a clear way to know your business and contact you.',
    screen: 'settings-business.png', screenAlt: 'Business information fields in Settings.',
    tool: { label: 'Open business settings', href: '/admin/settings' },
    before: 'Have your public business name, customer service email, and correct business address ready. Decide which phone number, if any, you want customers to use. Use an email account you check often.',
    steps: [
      'Open Settings and find Business & Contact. Read the values already saved before typing. This helps you avoid replacing a correct address or email by mistake.',
      'Enter Business Name. Use the name buyers see on your shop and receipts. Enter Business Email carefully. One wrong letter can send customer questions to the wrong place.',
      'Fill in Phone if you want to provide one. Then check Street, City, State / Region, Postal Code, and Country. These fields describe your business, not a sample customer.',
      'Choose Save Business Info and wait for Saved. Each settings section has its own save button. Saving business information does not save unsaved edits in Pricing or Shipping.',
      'Open the public website in another tab. Read the contact details wherever your site shows them. If a page has older wording typed into a section, use Pages to update that section too.',
      'Keep the address used for tax setup consistent with your real business location. Sales tax also needs its own state permit and Stripe Tax setup. A saved business address alone does not turn collection on.',
    ],
    example: ['If your shop name is Margaret Edmondson Art, use that spelling each time. A contact line such as “Questions about your artwork? Email our studio” is easier to understand than an unexplained email address.'],
    check: ['Reload Settings. The saved name, email, and address are still there.', 'Check the public contact link and make sure it points to the right email.'],
    troubleshoot: 'If you see Save failed, keep the page open and read the message. Check required fields and try again once. A success message in one section does not mean every section on the page was saved.',
  },
  {
    slug: '03-choose-fulfillment', title: 'Choose Lumaprints or fulfill orders yourself', group: '1. Set your foundation',
    summary: 'Decide who prints, packs, and ships, and understand the two saved price profiles.',
    screen: 'product-fulfillment.png', screenAlt: 'Fulfillment choices and the studio and Lumaprints price profiles.',
    tool: { label: 'Open fulfillment settings', href: '/admin/settings' },
    before: 'Fulfillment means getting a paid order to its buyer. Decide whether you want a print partner to do that work or whether you have the time, supplies, and equipment to do it yourself.',
    steps: [
      'Open Settings and find Orders & fulfillment. Read Use Lumaprints. When it is on, eligible prints use Lumaprints. When it is off, new artwork orders go to your studio. Originals stay with you.',
      'Choose Lumaprints when you want the partner to make and ship supported prints. You still supply a print-ready master artwork, choose valid sizes, check prices, and help customers when questions arise.',
      'Choose your studio when you make prints yourself, use your own local printer, or sell originals. You are responsible for the final selling price, production time, safe packing, shipping, and tracking.',
      'When creating a product, the starter asks which profile to prepare. That choice opens its editor; it does not switch the whole shop. Before changing the shop-wide fulfillment choice, open each important product and find Editing prices for. Select My studio or Lumaprints to prepare that profile. This menu chooses the profile you are editing; it does not switch the whole shop.',
      'Read Store currently uses beside that menu. Check that the profile the shop will use has ready prices and live options. Both profiles stay saved, so you can prepare the other one in advance.',
      'Change Use Lumaprints only after you have checked the new profile. Review Orders afterward. Existing purchases keep their saved fulfillment method; a settings change does not automatically move old work to another printer.',
    ],
    example: ['You sell one original and a small print. With Lumaprints on, the supported print can go to Lumaprints while you pack the original. With it off, you handle both new purchases. Changing the setting tomorrow does not rewrite yesterday’s order.'],
    check: ['Store currently uses matches the fulfillment choice you intended.', 'Each visible print has a valid price and a clear route to production.'],
    troubleshoot: 'A print missing after a switch may not be live or priced in the chosen profile. Studio-only sizes do not gain a Lumaprints mapping just because the switch is on. Check in-progress provider submissions before changing old orders.',
  },
  {
    slug: '04-upload-artwork', title: 'Upload artwork: display pictures and print files', group: '2. Build your catalog',
    summary: 'Use a clear shop picture for browsing and a sharp master file for printing.',
    screen: 'media.png', screenAlt: 'The Media library with Display Images, Product Photos, and Master Artworks tabs.',
    tool: { label: 'Open the media library', href: '/admin/media' },
    before: 'Find the best original image file you own. Keep a copy on your computer. A display image helps sell the art; a master artwork supplies the detail needed to print it. They serve different jobs.',
    steps: [
      'Open Media. Notice Display Images, Product Photos, and Master Artworks. Choose the tab that matches your task instead of uploading the same file into every area.',
      'Use Display Images for website pictures. Use a clear filename and add helpful alt text when the editor offers it. Alt text is a short description for someone who cannot see the picture.',
      'Use Product Photos for pictures attached to products. A straight-on view shows the artwork clearly. A room or framed view can help show scale, but it should not hide the main artwork.',
      'Open Master Artworks for the production file. Upload the high-resolution original, then wait for processing and read its status. Do not assume a small social-media picture can make a large print.',
      'Open the matching product and use Choose and save master artwork in its setup checklist, or scroll to its master artwork area. Select the master and choose Save Changes to attach it before preparing the crop. If you have not made a product yet, create its draft with a title and setup profile first, then continue in the full editor. A shop photo alone does not supply the production file Lumaprints needs.',
      'Check the crop and border choice before generating or publishing print sizes. The crop preview must show the same uncropped artwork as the original print file. If the tool warns that their shapes differ, choose a matching uncropped preview before saving. Look at the edges: a signature, face, or important detail should not be cut off. The finished print master’s width and height set its shape. Use the size checks in guide 6 to confirm each offered size fits that shape.',
    ],
    extra: [{ title: 'A print border is not a frame or a separate mat', paragraphs: ['The master tool’s Matte border adds a border to the prepared image. It does not order a physical mat board or choose a frame for the buyer. A product photo that shows a frame does not include that frame in the order. State clearly what you will deliver.', 'Finish the print area before generating sizes. If you later change the crop or border, check existing sizes again against the newly prepared master. Typing new measurements into the product’s description or Dimensions field does not reshape the print file.'] }],
    example: ['A photo of your painting hanging over a couch is a useful sales picture. It is usually the wrong print file because the couch and wall would print too. The master should show the artwork you actually want on the paper or canvas.'],
    check: ['The product has a clear main photo and the correct master attached.', 'The master is ready, and the crop preview includes the important parts of the artwork.'],
    troubleshoot: 'If processing fails, read the upload message and check the file type and size. If a print size fails resolution checks, use a sharper source or offer a smaller size. Enlarging a blurry picture does not add real detail.',
  },
  {
    slug: '05-add-product', title: 'Add your first product, step by step', group: '2. Build your catalog',
    summary: 'Start a draft with a name, then finish its pictures, artwork, sizes, and prices in the full editor.',
    screen: 'new-product.png', screenAlt: 'The Add a product screen: enter Product title, choose one setup profile, then choose Create draft & continue.',
    tool: { label: 'Start a product draft', href: '/admin/products/new' },
    before: 'You only need a product name and a choice of how to prepare it. You do not need an image, price, category, or size list to start. The first screen creates a draft so you can finish the real product setup before buyers see it.',
    steps: [
      'Open Products and start a new product. On Add a product, enter Product title, such as “Bluebonnets at Sunset.” You can change the name and the readable part of its web address later in the full editor.',
      'Under Choose how to prepare this product, select one profile. Lumaprints prepares partner-made prints. My studio prepares originals or prints you make and ship yourself. Printful starts a merchandise product that still needs its provider setup. This choice prepares the editor; it does not change the shop-wide fulfillment setting.',
      'Choose Create draft & continue once and wait for the full editor to open. The product starts with Draft status. Do not create a second copy if the page is slow. If an error appears, read it and check Products before starting over.',
      'Find Finish setting up your product in the full editor. Its links take you to Add product images, Choose and save master artwork for Lumaprints or Check fulfillment details for other profiles, Set pricing and product options, and Review and publish. Fill in Category, Description, Medium, and Dimensions where they apply. Describe exactly what the buyer gets, and say whether framing is included. Set Original artwork for a one-of-a-kind original; its price belongs in Base price.',
      'Add product images and choose Set Primary for the main sales photo. For Lumaprints, use Choose and save master artwork, select the correct master, and choose Save Changes to attach it to this product. Then prepare its crop or printed border and wait until the print master is ready. A product photo sells the artwork; the master supplies the file used to print it.',
      'Check Editing prices for. Lumaprints and My studio keep their own saved prices. The selected setup profile opens the matching pricing work for those two choices. Read Store currently uses before assuming you are editing the price buyers currently see. Printful still needs its own provider details; selecting it is not proof that the integration is ready.',
      'For Lumaprints, use guide 6 to choose an exact standard size or a custom size that follows the artwork’s shape, then review its automatic or manual price. A standard size with a different shape needs a reviewed crop or a separately prepared matching file; read both measurements before publishing. For My studio, use guide 7 to enter final prices, production approval, and shipping. You do not need a made-up Base price for a print-only draft.',
      'Save each area with its own control. Save Changes keeps the main product details. Save studio prices & shipping keeps studio options. Lumaprints rows and size dialogs have their own save or live controls. A completed product needs clear details, the correct files, and at least one ready option in the profile buyers will use.',
      'When everything is ready, use Review and publish in the setup checklist, set Status to Active in the full editor, and choose Save Changes. Open the public product. Check every offered option, its size and price, its photo, and the shipping promise. Keep the product Draft if a required file, price, or production step is unfinished.',
    ],
    example: ['Start by entering “Bluebonnets at Sunset” and choosing Lumaprints. Create the draft. In the full editor, add the photo and master, then prepare the available paper-print sizes. Write: “A fine art paper print of my Texas painting. Choose your size below. Frame is not included.” Check the real measurements and prices before making the product Active.'],
    check: ['Creating the draft opens that same product in the full editor.', 'The product’s active options have the right files, measurements, prices, and fulfillment profile.', 'The public product matches the final details you saved.'],
    troubleshoot: 'If you cannot find a price or category field on the first screen, continue to the full editor; the starter only needs a title and profile. If a finished listing is missing, check Draft versus Active and the option’s Live setting. If the wrong price appears, check which studio or Lumaprints profile the store currently uses.',
  },
  {
    slug: '06-print-sizes-and-variants', title: 'Create print sizes and make them live', group: '2. Build your catalog',
    summary: 'Understand familiar size labels, check the exact print measurements, and offer sizes that print clearly.',
    screen: 'standard-print-size.png', screenAlt: 'Example print-size editor showing an exact 16 × 20 choice and guidance to prepare a matching crop when the artwork has a different shape.',
    tool: { label: 'Choose a product to edit', href: '/admin/products' },
    before: 'A variant is one choice of a product, such as a 12 × 16 paper print. Attach a ready master artwork first. Know which materials and sizes you want to offer.',
    steps: [
      'Open Products, edit the artwork, and choose Lumaprints under Editing prices for. Find the print options. Each material has its own group, so check paper and canvas separately.',
      'Near-standard options show a familiar size on top and a small actual cropped size line directly below in the size column and storefront chooser. The smaller line gives the exact saved print measurements. Use it for framing. This display change does not resize the file or change the dimensions ordered from Lumaprints; an exact standard choice still needs a suitable prepared file.',
      'Review existing options before adding more. Read Label, Size, Cost, Margin %, Price, and Gross. Margin % is markup on print cost plus stored shipping cost. Use Generate S/M/L to suggest small, medium, and large sizes for a configured material. They follow your prepared master’s shape and the allowed size checks; they are not a list of guaranteed standard frame sizes. Read both dimensions before making an option live.',
      'Choose Add print size. Under Print size, select an exact option such as 16 × 20 in, or choose Custom — follow the artwork shape. A standard choice keeps its exact measurements. In Custom mode, changing one dimension updates the other to follow the master’s shape. Read both measurements and the size, resolution, and shape checks.',
      'If the exact size does not match your file’s shape, use Prepare crop for 16 × 20, or the button for your selected dimensions. In the crop tool, check Print shape. For a portrait 16 × 20, use 4:5 portrait — 8 × 10, 16 × 20. Move or resize the locked box and inspect every edge. The artwork outside the box will be removed.',
      'Choose Save crop only after you approve the crop. Saving starts the print-file work automatically. Keep the editor open while it says pending or processing; its status and measurements refresh automatically. The button says Processing crop… while the file is being prepared. When the print master is ready, close the crop window, return to Add print size, choose the exact size again, and review its checks and price. Existing sizes and prices do not automatically become a new size when the master changes.',
      'Review the price preview. Use the inherited markup, set a custom markup, or use a manual price if you need an exact amount. A manual price remains fixed when costs refresh, so you must check its profit yourself.',
      'Use Save as Draft while you are still deciding. Use Save & Publish only when the file, size checks, and price are ready. Existing drafts can be made available with the Live control.',
      'Use Refresh all prices when you need new provider costs. Read the result, including any skipped options. A refresh is not a promise that every draft is ready to publish.',
      'Visit the public product and select the new size. Check that the size label, amount, and material make sense to someone who has never seen the editor.',
    ],
    example: ['Shape means how wide an image is compared with its height. A 12 × 16 image has the same shape as 18 × 24: both become 3 × 4 when you divide each side by the same amount. A square 12 × 12 option is a different shape. Changing to a square may require a different crop or printed border; check the prepared master before selling it.', 'Suppose your prepared master is 6,400 pixels wide and 7,800 pixels tall. Choose a 16-inch width. First, divide 6,400 ÷ 16 = 400 pixels per inch. Then divide the height: 7,800 ÷ 400 = 19.5 inches. The matching print is 16 × 19.5. This is an example of keeping the file’s shape, not a diagnosis of any particular artwork or a promise that the print fits a 16 × 20 frame.'],
    extra: [{ title: 'Is 16 × 19.5 caused by DPI?', paragraphs: ['The unusual shape comes from the image’s pixel proportions or its saved crop. DPI is a separate print-quality check: it describes how much image detail fits into each printed inch. More pixels can support a larger sharp print, but changing a DPI label does not turn a different-shaped image into a 16 × 20 image.', 'For an easy 200-DPI example, a 3,200 × 4,000-pixel file can make a 16 × 20-inch print: 3,200 ÷ 200 = 16, and 4,000 ÷ 200 = 20. A 3,200 × 3,900-pixel file at the same detail level makes 16 × 19.5: 3,900 ÷ 200 = 19.5. The second file has a different shape, not a different rule for rounding 20.', 'The builder checks the detail required by the selected material. A 200-DPI canvas reference is not a promise that every paper or other material uses 200 DPI. Changing embedded DPI metadata alone does not add pixels, repair a crop, or change the width-to-height ratio. Use the actual print-master pixel dimensions and the builder’s checks.'] }, { title: 'Why a generated size may not fit a standard frame', paragraphs: ['The ready print master sets the width-to-height ratio. In Custom — follow the artwork shape, changing Width automatically updates Height; changing Height updates Width. Custom results use 0.05-inch steps. Exact standard choices keep their selected dimensions. Both paths must pass the material’s size limits, resolution check, and shape check; an option that fails may be blocked or omitted.', 'Generate S/M/L aims for long edges of 12, 20, and 30 inches. The other side follows the master’s shape. In the 6,400 × 7,800 example, a medium option with a 20-inch long edge is about 16.4 × 20. Small, medium, and large are starting suggestions, not guaranteed off-the-shelf frame measurements.', 'A true 16 × 20 print has a 4-to-5 shape. The example master has a different shape. Use the locked 4:5 crop only if you approve the parts of the image it removes. Matte border adds padding while keeping the selected crop’s shape; that setting alone does not fit an uncut image into a different shape or buy a physical mat. If every edge of the original art must remain, have a print professional prepare a matching bordered master for the exact size. Check the actual frame opening before promising a framed result.', 'Changing a shared master can affect the print setup for products using it. Review the image and every offered size again after changing its print area. Changing a size label or typing “16 × 20” into the description does not change the production file or the ordered dimensions.'] }],
    check: ['Only intended sizes are live.', 'Every live size passes its checks and shows the expected price on the product page.'],
    troubleshoot: 'If the print file is pending or processing, keep the editor open and wait for the automatic update; old crop measurements are not used during that work. If processing fails, read the reason shown, fix the file or crop problem, then open the crop tool and choose Save crop again to retry. You do not need to run a script. If the preview and original have different shapes, choose a preview of the same uncropped artwork before saving. If you change the crop after a file is ready, choose Save crop to apply your new selection; the previous ready file does not contain unsaved edits. If a standard size is blocked for shape, prepare and approve its matching crop, then return and select the size again. A material marked Run Lumaprints sync to enable still needs catalog setup. Do not bypass a failed check by changing only the label.',
  },
  {
    slug: '07-self-fulfilled-products', title: 'Set up originals and prints from your studio', group: '2. Build your catalog',
    summary: 'Set the final selling price, shipping choice, and work time for art you deliver yourself.',
    screen: 'product-fulfillment.png', screenAlt: 'My studio prices and shipping controls in the product editor.',
    tool: { label: 'Open products', href: '/admin/products' },
    before: 'Add up your real costs: paper or canvas, printing, frame, packing materials, postage, and your time. Decide how many days you need before shipping. Your studio price is a final price you enter.',
    steps: [
      'Edit the product and choose My studio under Editing prices for. Read Store currently uses so you know whether you are preparing a future profile or changing prices buyers currently see.',
      'For prints, enter Selling price ($) for each option you want to sell. The Lumaprints markup setting does not calculate this amount for you. Include your production costs and the money you want to keep.',
      'For an original, edit Base price in the main product editor. The studio original price points you back to that field. Describe the original’s exact size and materials so buyers know what they will receive.',
      'Choose the product’s shipping defaults. Shipping included means postage must fit inside your selling price. A flat fee adds the chosen shipping amount at checkout. Review any option-level shipping choice because it can override the product default.',
      'Set the lead time offered by the studio controls. This is the time you need to get the art ready, not a guarantee of carrier travel time. Tell buyers clearly when an item is made to order.',
      'For each print, open Production details & source approval. Fill in Production source reference and Print specifications, then inspect the actual file or sample for this size and finish. Only after that check, select “I have approved the production file or sample for this size and finish.” Originals do not need this print-approval checkbox.',
      'For a new studio print size, enter Option name, Material, Width (inches), and Height (inches). Confirm that your approved file, printer, and framing plan can deliver those exact measurements. Set a positive Selling price ($), then check Live in my studio. These studio sizes do not automatically become Lumaprints options.',
      'Choose Save studio prices & shipping. Save Changes separately if you changed the main product. Open the public listing and check a studio option before accepting orders.',
    ],
    example: ['Your materials cost $12, packaging costs $3, and postage costs $5. That is $20 before your time. At a $40 price with shipping included, $20 remains before tax, payment fees, and other expenses.'],
    check: ['Each studio print has approved production details, a positive selling price, dimensions, a material, and Live in my studio selected.', 'Your price covers the promised materials, packing, and shipping choice.'],
    troubleshoot: 'If saving a live print fails, check its positive selling price, material, dimensions, and production approval checkbox. If the public price did not change, check whether the shop currently uses Lumaprints. Editing My studio does not change that toggle. If an original price is locked here, change Base price above; originals do not require the print-approval checkbox.',
  },
  {
    slug: '08-organize-collections', title: 'Organize products into useful categories', group: '2. Build your catalog',
    summary: 'Help buyers find related art and understand how category pricing can affect products.',
    screen: 'products.png', screenAlt: 'The Products list with categories and product status controls.',
    tool: { label: 'Open products and categories', href: '/admin/products' },
    before: 'Choose a few names a buyer understands, such as Landscapes, Florals, or Originals. A category groups related products. Its default margin can also set pricing for products that inherit it.',
    steps: [
      'Open Products and choose Manage Categories. Read the existing list first. Reuse a good category instead of creating a nearly identical second one.',
      'Under Add a category, type its name. Leave the margin field blank to inherit the site default, or enter the markup you want for this category. Choose Add and wait for the success message.',
      'To rename a category, edit its name and click outside the field. Existing category rows save when the field loses focus. Wait for Category saved before closing the box.',
      'After creating a product draft, assign its category through the category control in Products or through Category in the full product editor. In the editor, choose Save Changes. A product’s primary category is the category used for its inherited markup.',
      'Think before changing a category margin. It can reprice automatic Lumaprints variants that inherit it. A product or variant override still wins, and a manual final price stays fixed. Review several product prices after a category change.',
      'Use the collection arrangement tool where it is offered to place a strong, varied selection first. Then open the public shop and check that buyers see a useful group of artworks.',
    ],
    example: ['Your site default markup is 100%. You set Florals to 150%. A floral print with a $20 landed cost becomes $50 if it inherits Florals. A floral product with its own 100% setting remains $40.'],
    check: ['Category names are clear and products are in the intended group.', 'Products that inherit a changed category margin show the prices you expected.'],
    troubleshoot: 'Deleting a category can leave its products uncategorized and change their inherited pricing. Review the warning first. If a price did not change, look for a more specific product, variant, or manual-price override.',
  },
  {
    slug: '09-understand-margins', title: 'Understand profit: studio prices, markup, and gross margin', group: '3. Price and collect correctly',
    summary: 'Follow easy dollar examples to see what the price settings do and what you really keep.',
    screen: 'pricing.png', screenAlt: 'Pricing settings for the default markup and shipping quote ZIP codes.',
    tool: { label: 'Open the live pricing controls', href: '/admin/settings#pricing' },
    before: 'Start with three words. Cost is money you spend. Price is money the buyer pays for the item. Profit is what remains after the costs you are counting. The platform’s Gross number counts print cost and stored shipping, not every business expense.',
    steps: [
      'Choose the profile you are using. My studio asks you to enter the final selling price. Lumaprints can build a price from costs and a markup. A manual Lumaprints price override lets you type an exact amount instead.',
      'Add print cost and the stored shipping allowance. This is called landed cost: what the art costs before your extra amount is added. Suppose printing costs $15 and shipping costs $5. Landed cost is $20.',
      'Apply the Margin % input. On this platform that input means markup: an extra percentage of cost. At 100%, add another $20 to the $20 cost. The selling price becomes $40. It does not mean you keep the whole sale.',
      'Find the gross profit dollars. Subtract the $20 landed cost from the $40 price. That leaves $20. Now divide that $20 by the $40 selling price. Half the price remains, so gross margin is 50%.',
      'Try a smaller markup. At 50% markup, half of $20 is $10. Add $10 to the $20 cost and sell for $30. Gross profit is $10. $10 divided by $30 is about 33.3%, so 50% markup is about 33.3% gross margin.',
      'Account for money the Gross column does not subtract. Payment fees, discounts, included sales tax, supplies outside the quoted cost, your time, ads, rent, returns, and replacements can all reduce what you keep.',
      'Check a real order after changing prices. Compare its sale amount, discount, tax, shipping revenue, and actual expenses. A planned gross margin is a pricing guide; it is not a bank balance or a promise of take-home profit.',
    ],
    example: [
      'Start with the dollars. Printing costs $15. Stored shipping costs $5. Add them: $15 + $5 = $20. This $20 is the cost used by the automatic pricing tool. A 100% markup means adding one more whole copy of that cost. Add $20 to your original $20: $20 + $20 = $40 selling price.',
      'What does percent mean? Percent means “out of 100.” Divide a percentage by 100 before multiplying dollars by it. So 100% becomes 100 ÷ 100 = 1. That 1 means one whole amount. A 50% markup becomes 50 ÷ 100 = 0.5, which means half an amount. A 150% markup becomes 150 ÷ 100 = 1.5, which means one and a half amounts.',
      'Here is the longer method with every step: (1) Add costs: $15 + $5 = $20. (2) Turn the markup into a number: 100 ÷ 100 = 1. (3) Find the extra dollars: $20 × 1 = $20. (4) Add the cost and the extra dollars: $20 + $20 = $40. The × sign means multiply; the ÷ sign means divide.',
      'The short formula does those same steps together: price = (print cost + stored shipping cost) × (1 + markup ÷ 100). The first 1 means “keep the original cost.” The markup ÷ 100 part tells us how much EXTRA cost to add. Neither 1 is a dollar charge. Parentheses group the calculations we finish first.',
      'Put the example numbers into every blank: ($15 + $5) × (1 + 100 ÷ 100). First finish the costs: $20 × (1 + 100 ÷ 100). Divide 100 by 100 before adding: $20 × (1 + 1). Add 1 + 1: $20 × 2. Finally multiply: $40. The × 2 means “two copies of the $20 cost.” That is exactly where the 2 came from.',
      'Now find gross profit: $40 selling price − $20 counted costs = $20 left before other expenses. To find gross margin, ask what share of the SELLING PRICE is left: $20 ÷ $40 = 0.5. Turn that into a percentage: 0.5 × 100 = 50%. Half of the buyer’s $40 covers the counted costs, and half remains.',
      'Markup and gross margin use different starting amounts. Markup compares the extra $20 with your $20 COST: $20 ÷ $20 × 100 = 100%. Gross margin compares that same extra $20 with your $40 PRICE: $20 ÷ $40 × 100 = 50%. The profit dollars are the same; the number you divide by changes. Enter 100 in the platform’s Margin % field to get this example’s 50% gross margin.',
      'Manual-price example: you choose a $50 selling price for the same $20 cost. Subtract: $50 − $20 = $30 gross profit. Divide by the selling price: $30 ÷ $50 = 0.6. Multiply by 100: 0.6 × 100 = 60% gross margin. Its matching markup is $30 ÷ $20 = 1.5, then 1.5 × 100 = 150%. A manual price stays at the amount you enter until you change or clear it.',
      'Discount example: a $10 discount turns a $40 sale into $30. The $20 cost stays $20. Only $10 remains before other expenses. If payment fees were $1 for this example, $9 would remain. The $1 is a made-up fee for easy math, not a quoted Stripe fee.',
    ],
    extra: [
      { title: 'Compare 0%, 50%, 100%, and 150% markup', paragraphs: ['Keep the same $20 cost in each example. At 0% markup: 0 ÷ 100 = 0; $20 × 0 = $0 extra; $20 + $0 = $20 selling price. Gross profit is $0 before other expenses.', 'At 50% markup: 50 ÷ 100 = 0.5; $20 × 0.5 = $10 extra; $20 + $10 = $30 selling price. Gross margin is $10 ÷ $30 × 100, or about 33.3%.', 'At 100% markup: 100 ÷ 100 = 1; $20 × 1 = $20 extra; $20 + $20 = $40 selling price. Gross margin is $20 ÷ $40 × 100 = 50%.', 'At 150% markup: 150 ÷ 100 = 1.5; $20 × 1.5 = $30 extra; $20 + $30 = $50 selling price. Gross margin is $30 ÷ $50 × 100 = 60%.'] },
      { title: 'If you want a target gross margin', paragraphs: ['Suppose costs are $20 and you want half of the price to remain before other expenses. Half must cover costs, so the $20 cost needs to be half of the price. Two halves of $20 make a $40 selling price. That gives a 50% gross margin. Enter a 100% markup or a $40 manual price.', 'The planning formula is price = cost ÷ (1 − target gross margin ÷ 100). The 1 means the whole selling price. Subtract the profit share to find the share available to cover costs. For a 50% target: 50 ÷ 100 = 0.5; 1 − 0.5 = 0.5; $20 ÷ 0.5 = $40. Dividing by one-half asks how big the whole must be when its half is $20.', 'For a 60% gross target: 60 ÷ 100 = 0.6; 1 − 0.6 = 0.4. That leaves 40% of the price to cover your $20 cost. $20 ÷ 0.4 = $50. Check it: $50 − $20 = $30 profit; $30 ÷ $50 × 100 = 60%. The matching markup is $30 ÷ $20 × 100 = 150%. Enter 150 in Margin %, or enter $50 as a manual price. A 100% gross target is impossible when the product has a real cost: some of the sale must pay that cost.'] },
      { title: 'Tax changes the money you keep', paragraphs: ['Separately added sales tax belongs to the state; it is not your profit. In included mode, tax comes out of the displayed price. For an easy example using a made-up 10% tax rate, a $44 tax-included sale contains $40 of sales and $4 of tax. With $20 of costs, $20 remains before fees and other expenses. Actual checkout uses the applicable tax rate.', 'The variant Gross column uses the listed price and stored print/shipping costs. It does not back out a particular buyer’s included tax or order discount. Use the order’s actual figures to work out the final result.'] },
      { title: 'Your studio uses your own cost plan', paragraphs: ['My studio Selling price is the final amount you enter. Add printing, framing, packaging, postage, and an amount for your work before deciding your price. The site default markup does not automatically rewrite studio selling prices. If you include shipping, build its cost into your plan. If you add a flat shipping fee, compare that fee with what you really spend.'] },
    ],
    check: ['You can explain why 100% markup gives 50% gross margin.', 'You know whether your live price is automatic, a manual override, or a studio selling price.'],
    troubleshoot: 'If profit looks too high, check whether you forgot shipping, included tax, fees, or your time. If a markup change does nothing, look for a manual price or the studio profile. A zero markup covers only the counted landed cost.',
  },
  {
    slug: '10-change-margins', title: 'Change margins for the shop, a category, or one size', group: '3. Price and collect correctly',
    summary: 'Use the right control, understand which setting wins, and verify the price afterward.',
    screen: 'pricing.png', screenAlt: 'The Pricing section with Default Margin and Save Pricing Settings.',
    tool: { label: 'Change the shop default markup', href: '/admin/settings#pricing' },
    before: 'Read article 9 first. Margin % means markup on landed cost. Write down one product’s current cost and price so you can compare after saving. Decide whether the change should affect many products or only one option.',
    steps: [
      'For the broadest default, open Settings → Pricing. Enter Default Margin (%) and choose Save Pricing Settings. This is used when no more specific markup is set. A saved change reprices eligible automatic variants.',
      'For a group, open Products → Manage Categories. Edit Default margin % for that category and click outside the field to save. Blank means inherit the site default. Zero means 0% markup; it does not mean inherit.',
      'For one product, open its editor and find Default margin (%). Enter a markup if that product should differ from its category, then choose Save margin + refresh prices. Leave it blank to inherit.',
      'For one Lumaprints size, choose Lumaprints under Editing prices for and edit the row’s Margin %. That is the most specific percentage. Clear the field to use the product’s inherited amount. Row edits save automatically after a short pause without a success toast. Pause before leaving, watch for an error message, then reload and confirm the value stayed saved.',
      'Check for a star beside the price. A manual price override wins over all markup settings. Use the price edit pencil and clear the amount if you want automatic pricing again. Refreshing prices does not clear a manual override.',
      'Review the result on the public product. If costs also need updating, use the quote refresh control and read its report. Review skipped options individually. Refresh prices (use defaults) uses fallback costs; it is not a fresh provider quote.',
      'For My studio, change Selling price ($) in the studio profile instead. Choose Save studio prices & shipping. Changing a Lumaprints markup does not set your studio’s final prices.',
    ],
    example: ['The order of authority is: manual final price first; otherwise variant markup → product markup → primary category markup → site markup → 100% fallback. Read that arrow as “if blank, look at the next place.”', 'Site is 100%, category is 150%, product is blank, and variant is blank. A $20 cost sells for $50. Set that variant to 50% and it sells for $30. Set a manual price of $45 and it stays $45 until you clear it.'],
    check: ['The save succeeded and survives a reload.', 'At least one affected public size changed correctly, and an intentionally overridden size stayed correct.'],
    troubleshoot: 'If a price stayed the same, inspect the full chain before saving repeatedly. Confirm which fulfillment profile is live. Do not erase a manual price unless you want future cost refreshes to change it.',
  },
  {
    slug: '11-shipping-and-profit', title: 'Choose shipping and protect your profit', group: '3. Price and collect correctly',
    summary: 'Understand included shipping, flat fees, and the shipping cost inside automatic prices.',
    screen: 'shipping.png', screenAlt: 'Shipping settings and shipping choices for artwork orders.',
    tool: { label: 'Open shipping settings', href: '/admin/settings' },
    before: 'Shipping has two sides: what you pay the carrier or printer, and what the buyer pays you. They are not always the same. Know your package size, packing cost, destination limits, and likely postage.',
    steps: [
      'Open Settings → Orders & fulfillment and expand the studio defaults. Review Default shipping, Ships within (calendar days), and My studio rates also cover Alaska and Hawaii. Choose Save studio defaults after changing those controls.',
      'Edit a product and choose the profile you use. In My studio, choose shipping included or a flat fee. Check the product default and each option because an option can have its own shipping rule.',
      'For Lumaprints, review Lumaprints profile shipping. Shipping included keeps the buyer’s shipping charge inside the item price. Flat fee per item adds your chosen amount. Use shipping integration uses the integration’s shipping behavior.',
      'Understand the automatic cost allowance. Pricing adds printing and the stored shipping allowance before applying markup. The CONUS Quote Zips setting samples contiguous U.S. ZIP codes and uses the highest quoted cost in that price calculation.',
      'Check Alaska and Hawaii separately. The integrated provider path can add the extra quoted shipping cost above the allowance already included. Studio delivery to those states depends on your fulfillment policy. Do not promise delivery to an unsupported address.',
      'Save the section you changed. Then put one item in the cart and check shipping for a supported destination. Try quantity two if you use a fee per item: the fee can be charged twice.',
    ],
    example: ['Your $40 selling price already includes a $5 shipping allowance. If your real postage is $7, you spend $2 more than planned. If you also set a $5 flat fee, the buyer pays $45 before separate tax. Make sure that extra charge is intentional and clearly explained.'],
    check: ['The checkout shipping line matches the active product and option policy.', 'Your price plan counts packaging and actual postage, not only the displayed fee.'],
    troubleshoot: 'A quote failure should be fixed before accepting the destination. Do not treat an error as free shipping. If shipping seems doubled, check the amount already built into your selling price and the added flat fee.',
  },
  {
    slug: '12-sales-tax-and-nexus', title: 'Sales tax and nexus: included or added separately', group: '3. Price and collect correctly',
    summary: 'Learn what nexus means, select the right states, and choose how buyers see sales tax.',
    screen: 'sales-tax.png', screenAlt: 'Sales tax settings with collection, included pricing, and nexus state choices.',
    tool: { label: 'Open the live sales tax settings', href: '/admin/settings#sales-tax' },
    relatedTools: [{ label: 'Open sales tax on your dashboard', href: '/admin#sales-tax' }],
    before: 'Sales tax is money you collect for a state. Nexus means your business has a strong enough connection to that state that it may require you to collect tax. A studio, office, worker, or inventory there can create a physical connection. Enough sales into a state can also create an economic connection.',
    steps: [
      'List where your business actually operates and where it has other connections. Margaret’s business has a Texas nexus. Review other states if you add locations, inventory, workers, or enough sales there. Each state has its own rules.',
      'Register with the state when required. A checkbox in ArtByME does not issue a permit. Use the official registration links in the nexus help, keep the permit details, and note your filing schedule.',
      'Set up Stripe Tax for the connected Stripe account. Add the correct head office address, an appropriate default product tax code, and active tax registrations for the states you are ready to collect in. Recording a registration in Stripe does not itself get you a state permit.',
      'Open Settings → Sales tax. Select the states where you have nexus and are registered to collect. Choose one tax option: Off, Include tax in my prices, or Add tax at checkout. The app checks tax setup and active registrations when you save a collecting option; fix any named missing setup before trying again.',
      'Choose Include tax in my prices to keep applicable tax inside your displayed prices. Choose Add tax at checkout to calculate applicable tax and add it above those prices. Off collects no sales tax through this setting. Select only one option, choose Save sales tax, then read the saved option and selected states again.',
      'At checkout, the buyer provides a full shipping address. When the shipping state is selected, Stripe Tax applies the tax rules for that transaction. When the shipping state is not selected, this seller’s tax system adds no sales tax. Selection does not make an otherwise exempt item taxable.',
      'Keep records and file returns on the state’s schedule. Collecting money at checkout does not automatically file a state return or pay it for you. Check your state account even during a period with no tax collected.',
    ],
    example: ['These examples use an illustrative 8.25% tax rate, one taxable item, and no shipping charge or discount. Actual checkout calculates the applicable rate. Percent means “out of 100,” so 8.25% becomes 8.25 ÷ 100 = 0.0825 before we multiply it by dollars.', 'Separate tax, step 1: list the item at $100. Step 2: find the tax: $100 × 0.0825 = $8.25. Step 3: add it: $100 + $8.25 = $108.25 paid by the buyer. Step 4: set aside $8.25 for tax. The remaining $100 is sales money before your product costs, fees, and other expenses.', 'Included tax, step 1: suppose your listed price is $108.25 and already contains tax. The whole amount before tax is 100% of itself. Adding 8.25% tax makes 108.25% of that original amount. Turn that percentage into a number: 108.25 ÷ 100 = 1.0825. Another way to get the same number is 1 + (8.25 ÷ 100) = 1 + 0.0825 = 1.0825. The 1 stands for the original sale; 0.0825 stands for the extra tax share.', 'Included tax, step 2: work backward to find the sale before tax. $108.25 ÷ 1.0825 = $100. Step 3: subtract that sale from the amount paid: $108.25 − $100 = $8.25 tax. Step 4: set aside the $8.25. The buyer still pays the listed $108.25. Division undoes the multiplication that put tax into that total.', 'Keep the SAME $100 listed price when comparing the two collecting options. With separate tax, the buyer pays $108.25 and your sales before expenses are $100. With included tax, the buyer pays $100 total. Work backward: $100 ÷ 1.0825 = about $92.38 in sales; $100 − $92.38 = about $7.62 in tax. Changing the tax option does not raise your product price to protect your profit. Review the price yourself.', 'Why not multiply an included total by 8.25%? That percentage applies to the sale BEFORE tax. Multiplying the whole tax-included total would also apply the rate to tax already inside it. Divide the total by 1.0825 first, then subtract the result from the total. Checkout handles its own currency rounding; these examples round to cents.'],
    extra: [
      { title: 'What each control means', paragraphs: ['Select one of three choices. Off means this setting collects no sales tax. You can save your state choices for later. Choosing Off does not remove a legal collection duty or cancel a permit.', 'Include tax in my prices takes applicable tax from the listed price. Add tax at checkout adds applicable tax above the listed price. These are the two collecting options. Choose one; included does not mean tax-free.', 'States where your business has nexus limits the delivery states where this system collects. Choose the states supported by your collection duties and active registrations. Then press Save sales tax. Choosing a tax option or checking a state on the screen is a draft until the save succeeds. Read the setup message, reload, and confirm your saved choices.'] },
      { title: 'Follow two buyers through a Texas-only setup', paragraphs: ['Assume Include tax in my prices or Add tax at checkout is selected, Texas is the only selected state, and its registration is active. A buyer ships a taxable item to Texas: checkout calculates applicable tax. Separate mode adds it; included mode identifies the portion already in the price.', 'A second buyer ships the same item to a state you did not select. This seller’s system collects $0 sales tax for that destination. In included mode, the listed price stays the same; the system does not subtract a pretend Texas tax amount or give an automatic tax discount.', 'A buyer can live in another state and send a gift to Texas. The Texas delivery address is what matters for this shipped order. If you later need to collect in another state, obtain the required registration, add it in Stripe, select that state here, and save. A selection cannot create the permit for you.'] },
      { title: 'Follow the money from sale to profit', paragraphs: ['Use the same $100 price and assume your counted product costs are $40. With separate tax at our example rate, the buyer pays $108.25. Set aside $8.25 tax, leaving $100 sales. Subtract $40 costs: $60 remains before fees and other expenses.', 'With included tax at the same $100 price, the buyer pays $100. Set aside about $7.62 tax, leaving about $92.38 sales. Subtract $40 costs: about $52.38 remains before fees and other expenses. That is why changing the tax mode can change what you keep even when your product price stays the same.'] },
      { title: 'Use the report controls, step by step', paragraphs: ['Step 1: open Dashboard and find the sales report. Under Reporting period, select Last 30 days, Last 90 days, This quarter, Last 365 days, or This year. Read the start and end dates shown below the controls. These are America/Chicago calendar days, including today. This quarter and This year begin at the calendar quarter or year, not your permit’s filing deadline.', 'Step 2: wait for the report to load. Use Refresh report after a new order or a recorded refund. The date choice selects orders by when they were created, not by a separate paid date. The report uses the refund information known now, so an old group of orders can change after a later full refund.', 'Step 3: find Tax by state. Read Included tax, Added tax, and Recorded tax. Then read Full-refund tax and Net recorded tax. Look at Review for missing amounts or refunds needing attention. A state marked Not selected now can still have real tax from earlier sales.', 'Step 4: use Download CSV to save the state-tax summary as a spreadsheet-friendly file. It includes the date range and report basis. It does not export the dashboard’s recent-order list. Keep that file with your order, payment, refund, and state-payment records. It is a review aid, not a tax return submitted to the state.', 'Step 5: if you need to change future collection, choose Sales tax settings. Changing those settings does not rewrite the amounts saved on earlier orders.'] },
      { title: 'Track the tax recorded for each state', paragraphs: ['Open Dashboard from the admin menu, then find Sales tax tracker, or use the link near the top of this guide. It groups stored tax by state and separates tax included in prices from tax added at checkout. It uses the tax saved with each purchase. It does not apply today’s tax rate to old orders, and it keeps a state’s history even if you later remove that state from your collection settings.', 'Recorded tax to set aside is based on recorded tax minus tax on fully refunded orders. It is a record to review, not a promise of your exact unpaid state bill. Payments you make to the state are not tracked here. Partial refunds and other filing adjustments may still need review.', 'An empty report or $0 recorded tax does not prove that you owe no tax. Older orders may be missing tax details. A missing state or an unknown payment mode needs attention. Read the warnings and compare your order records, Stripe records, and state account before filing.'] },
      { title: 'Add two Texas orders, then check a refund', paragraphs: ['Use our illustrative 8.25% rate and assume both orders belong in the report. Order A uses Add tax at checkout: $100 sales + $8.25 tax = $108.25 paid. Order B uses Include tax in my prices: $100 paid ÷ 1.0825 = about $92.38 sales; $100 − $92.38 = about $7.62 tax. The report records $8.25 added tax and $7.62 included tax.', 'Add the tax from both orders: $8.25 + $7.62 = $15.87 recorded Texas tax. Now suppose all of Order A’s payment is refunded and that full refund is recorded. Its tax credit is the full $8.25. Subtract it: $15.87 − $8.25 = $7.62 net recorded tax left to review.', 'If Order B instead has a partial refund, the tracker does not guess how much tax belongs to that refund. Review the actual refunded items, shipping, and tax in your payment records. A partial refund made directly in Stripe may also need to be checked there. If you already paid some tax to Texas, compare that payment separately; this tracker does not subtract state payments.'] },
      { title: 'Shipping, discounts, and the final address', paragraphs: ['The app uses Stripe Tax with the order’s shipping address, product tax setup, and registered locations. It does not apply one flat rate to every address in a state. Tax treatment of shipping and local taxes follows the calculation service’s rules.', 'A separate-tax math example with taxable shipping: a $100 item minus a $10 merchandise discount leaves $90. Add $5 taxable shipping to get $95 subject to tax. At an illustrative 8% rate, 8 ÷ 100 = 0.08; $95 × 0.08 = $7.60 tax; $95 + $7.60 = $102.60 total. This simplified example assumes both the item and shipping are taxable at that rate. Actual rules can differ.', 'With tax collection enabled, the buyer must provide a complete shipping address. If changing the final address changes the tax or total, checkout shows the update and asks the buyer to review it before pressing Pay again. If an address or tax setup cannot be verified, follow the displayed error before paying.'] },
    ],
    check: ['The saved mode and nexus states match your permits and intended policy.', 'Test a selected-state address and an unselected-state address and compare the tax line.'],
    troubleshoot: 'A registration error usually means the selected state is not active in Stripe Tax or the account setup is incomplete. A zero tax result can also reflect tax rules or an unselected shipping state. Check the actual address, product tax classification, permit setup, and saved settings. Tax-enabled orders below $0.50, or discounts that leave only shipping to pay, need help from the studio; automatic free-order checkout is not supported.',
    sources: [ { label: 'Texas sales tax permit registration', href: 'https://comptroller.texas.gov/taxes/permit/' }, { label: 'Stripe Tax setup for custom checkout', href: 'https://docs.stripe.com/tax/payment-intent/simplified' } ],
  },
  {
    slug: '13-texas-sales-tax-setup', title: 'Set up Texas sales tax for Margaret’s studio', group: '3. Price and collect correctly',
    summary: 'Register with the Texas Comptroller, connect tax collection, and use the right included-tax wording.',
    screen: 'sales-tax.png', screenAlt: 'Texas nexus selection and included or separate sales tax controls.',
    tool: { label: 'Set up Texas in sales tax settings', href: '/admin/settings#sales-tax' },
    relatedTools: [{ label: 'Open sales tax on your dashboard', href: '/admin#sales-tax' }],
    before: 'Texas calls its tax agency the Comptroller of Public Accounts. Margaret’s Texas studio is a physical business connection. Do not assume a rule for a remote seller with no Texas presence removes the duties of a business physically in Texas.',
    steps: [
      'Open the official Texas sales tax permit page linked below. Read the application instructions and gather the business information it requests. Apply through the state’s own process if you need a permit.',
      'Keep your permit details and the filing schedule the Comptroller gives you. Know the date collection should begin. A sales tax permit, collecting tax, and filing returns are three separate jobs.',
      'In Stripe Tax, enter the real business head office address and add the active Texas registration for your permit. Check the tax classification for the art you sell. Then return to ArtByME sales tax settings.',
      'Open the live settings link above. Under Find a state, search Texas and select Texas. Select Include tax in my prices to collect within the listed price, or Add tax at checkout to collect above it. Select only one option, then press Save sales tax. If the save reports missing setup, fix the named issue in Stripe first. Reload and confirm Texas and your one selected tax option still show your saved choices.',
      'For included prices, show this clear statement prominently: “Texas state and local sales and use tax is included in the sales price.” The platform uses this disclosure in its included-tax flow. Check the shop’s buying screens and the order or receipt view after saving.',
      'For separate prices, check that checkout shows a distinct sales tax amount and the final total before payment. The buyer’s full shipping address is needed to calculate the applicable amount.',
      'Review one Texas address and one address in a state you have not selected. Keep the order’s tax records. File and pay through the Comptroller on your required schedule; the ArtByME tax setting does not send the tax return for you.',
    ],
    example: ['Texas has a 6.25% state sales tax, and local taxes can add up to 2%. A combined 8.25% is an example, not the correct rate for every sale. For a taxable $100 sale at that example rate, separate tax adds $8.25. At a $100 tax-included price, the pre-tax sale is about $92.38 and the tax portion about $7.62.', 'If you want to keep $100 in sales before your costs and tax at an example 8.25% rate, an included price would be $108.25. If you keep an included price at $100 instead, part of that $100 must be set aside for tax.'],
    extra: [
      { title: 'Why the full address and business setup matter', paragraphs: ['Texas local sales tax can depend on where the seller’s business takes the order, with additional local use tax rules for the delivery location. The correct result is not always “use the destination’s highest rate.” The app relies on Stripe Tax and your accurate business and registration setup to calculate the transaction.', 'Texas offers a special single local use tax option to qualifying remote sellers. A seller based in Texas cannot simply choose that remote-seller option for convenience. Use the Comptroller’s guidance for your type of business.'] },
      { title: 'Review Texas on your dashboard before filing', paragraphs: ['Open the Dashboard’s tax section using the link near the top of this guide. Use Reporting period to choose the dates you want to review, then find TX under Tax by state. Compare Included tax, Added tax, Full-refund tax, and Net recorded tax. Read every refund or missing-data warning before relying on the numbers.', 'The selected period groups orders by when they were created, using America/Chicago calendar days. There is no separate paid-date field for this report. Refund information reflects what is known now, so a later full refund can change the report for an earlier group of orders. That is different from a tax return that follows the state’s own reporting rules.', 'Compare the tracker with your Stripe records and Texas account. Keep sales, refunds, discounts, shipping, and tax together. Subtract payments you already sent to the state in your own records; state payments are not stored in this tracker. Follow the Comptroller’s filing schedule, which can differ from your monthly review habit.'] },
    ],
    check: ['Texas is selected and its Stripe registration is active.', 'Included mode shows the Texas disclosure, or separate mode shows an added tax line.', 'You know where to file and when the next return is due.'],
    troubleshoot: 'If activation fails, check Stripe Tax setup and the Texas registration before changing rates. If a result seems wrong, verify the seller address, shipping address, and product tax code. Ask the Comptroller or your tax professional about unusual sourcing or exemption cases.',
    sources: [
      { label: 'Apply for a Texas sales tax permit', href: 'https://comptroller.texas.gov/taxes/permit/' },
      { label: 'Texas collection FAQ and included-tax disclosure', href: 'https://comptroller.texas.gov/taxes/sales/faq/collection.php' },
      { label: 'Texas local sales and use tax rules', href: 'https://comptroller.texas.gov/taxes/publications/94-105.php' },
      { label: 'Texas tax guidance for online sellers', href: 'https://comptroller.texas.gov/taxes/publications/94-171.php' },
    ],
  },
  {
    slug: '14-edit-page-words', title: 'Make a small wording change on a page', group: '4. Make the shop yours',
    summary: 'Edit one section, save it, and check the live page without losing your place.',
    screen: 'pages.png', screenAlt: 'The Pages section editor used to change website wording.',
    tool: { label: 'Open the page section editor', href: '/admin/pages' },
    before: 'Open the public page and find the exact words you want to change. Write your new sentence first. Most built-in pages use the section editor, where you can edit words without writing code.',
    steps: [
      'Open Pages in the admin menu. Choose the page that contains the wording. The page picker chooses the page; the tabs below choose a section within that page.',
      'Choose the section whose name matches the part of the website you are changing. A headline near the top may be in a hero or introduction section. Read the field labels and current values to confirm you are in the right place.',
      'Click the text field and replace only the words you intended. Keep a heading short. For a paragraph, use complete sentences. If you are editing a button, use a clear action such as “Shop prints.”',
      'If you change a link, check its destination too. The text on a button and the address it opens are separate things. A new button label does not automatically change where it goes.',
      'Choose Save section. Wait for All changes saved. The save applies to that section and goes live immediately. If another tab has a dot or says Unsaved changes, save that section separately.',
      'Open or refresh the public page. Read the sentence in its real layout, click any changed link, and check the narrow phone view if possible. A sentence that fits on a desktop can be long on a phone.',
      'If you change your mind before saving, use Discard. If you already saved, open the revision menu for that section and review an earlier version. The editor keeps the last five section versions.',
    ],
    example: ['Before: “Explore my work.” After: “Bring a little Texas color into your home.” For a button, “Shop art prints” tells the buyer exactly what happens next. You can make this change in the text field without changing the whole page.'],
    check: ['The editor says All changes saved.', 'The live page shows the new sentence and any link goes to the intended place.'],
    troubleshoot: 'If you do not see the change, confirm you edited the right page and section, then refresh the public page. If the old text appears elsewhere too, it may belong to a different section that needs its own edit.',
  },
  {
    slug: '15-add-and-publish-page', title: 'Undo a page change and restore a saved version', group: '4. Make the shop yours',
    summary: 'Use Discard before saving or History after saving to recover the wording you want.',
    screen: 'page-editor.png', screenAlt: 'The page section editor with History open and its Last 5 versions list.',
    tool: { label: 'Open page sections and History', href: '/admin/pages' },
    before: 'Find the exact page and section that changed. Page history belongs to one section at a time. It does not restore the whole website, product catalog, or orders. Write down any current wording you want to keep before restoring an earlier version.',
    steps: [
      'Open Pages. Use the Editing button, such as Editing About, to choose the right page. Then choose the section tab that contains the words or picture you want to recover.',
      'Read the save status. If the change is still unsaved, choose Discard to return that section to its last saved content. Discard is for your current unsaved edits; it does not reach back through older versions.',
      'If the change was already saved, choose History near the section fields. The menu shows Last 5 versions with times and the editor name when available. Use the date and time to identify the version you need.',
      'Before using Revert, remember it restores the whole selected section. If the section also contains a good new photo or link, restoring older wording may restore that photo or link too. Note any part you want to add back afterward.',
      'Choose Revert beside the intended version and read the confirmation. Confirm only when you want that section restored. Wait for Reverted and let the editor reload its saved content.',
      'Open the public page and check the result. Section saves and restores go live immediately. Read the text, check the picture, and click the links in that section before moving on.',
      'If you picked the wrong version, open History again. The current version is saved automatically when you revert, so you can return to it while it remains in the five-version history. For a tiny mistake, directly edit the field and Save section instead.',
    ],
    example: ['Yesterday your About introduction was correct. Today a longer sentence was saved and does not fit well. Open About, select the introduction section, and use History to restore the earlier saved version. Then check the live About page. The shop’s product descriptions and order records are unaffected.'],
    check: ['The correct page section shows the intended text and pictures.', 'The public page agrees with the saved editor, and other sections still look right.'],
    troubleshoot: 'No revisions yet means there is no saved history to choose from for that section; the next save creates its first revision. Only the last five versions are kept. If the needed version is older, use your own copy of the text and save it as a new edit.',
  },
  {
    slug: '16-update-storefront-images', title: 'Change website pictures and product photos', group: '4. Make the shop yours',
    summary: 'Choose the right picture, describe it clearly, and check its crop on the live page.',
    screen: 'media.png', screenAlt: 'The Media library used to select display images and product photos.',
    tool: { label: 'Open images in Media', href: '/admin/media' },
    before: 'Decide whether you are changing a website section image, a product photo, or a print master. This article covers what visitors see. Changing a visible picture does not automatically replace the file used to print an order.',
    steps: [
      'For a website section, open Pages, select the correct page and section, and find its image field. Use the image picker to choose a library image or upload the image you prepared.',
      'For a product, open Products and edit that artwork. Use its image area to add a picture from the library or upload one. Pick the clearest artwork view as the primary image.',
      'Write useful alt text where the image tool provides it. Describe what matters in one short sentence. “Bluebonnets beside a Texas fence at sunset” is more helpful than “image1” or a long list of search words.',
      'Review the crop before saving. A wide website banner may cut off the top and bottom of a tall painting. Choose a picture that fits the space and keep the important subject away from the edges.',
      'Save the page section or product changes using the control for that area. Wait for the success message. Then refresh the public page and look at both a wide screen and a narrow phone view.',
      'Keep images that other pages still use. Before deleting a library item, check where it appears. Replacing one photo is usually easier to verify than removing a shared image and repairing several pages.',
    ],
    example: ['You want a new home-page banner. Choose a wide photo that leaves space around the artwork. For the product’s main photo, choose a straight-on view so buyers can see the full piece. The best banner and best product photo may be different files.'],
    check: ['The right picture appears on the right page and its important details remain visible.', 'Product options still use the correct print master after any display-image edit.'],
    troubleshoot: 'If the picture looks soft, start with a sharper original. If a face or signature is cut off, adjust the crop or choose another image. If the image did not change, check whether you saved the section that contains it.',
  },
  {
    slug: '17-test-your-store', title: 'Check your shop before the first customer buys', group: '5. Sell and run the studio',
    summary: 'Walk through the customer path and catch missing prices, unclear words, and checkout surprises.',
    screen: 'storefront.png', screenAlt: 'The public ArtByME storefront as a customer sees it.',
    tool: { label: 'Open your public shop', href: '/' },
    before: 'Finish a product, its active fulfillment profile, shipping settings, and tax setup. Keep a note with the expected item price and shipping behavior. You can inspect a cart without placing an order.',
    steps: [
      'Open the public shop in a separate tab. Start at the home page and follow the links a new buyer would use. Check that contact information, product pictures, and basic wording are clear.',
      'Open an active product. Read the title, description, size, material, and framing details. Select each important option and compare its shown price with the price you intended in the active profile.',
      'Add one item to the cart. Change quantity if the product allows it, then remove an item and add it again. Check that the item name, chosen size, quantity, and subtotal remain correct.',
      'Go to checkout and enter a complete supported shipping address. Read the item total, discount if any, shipping, sales tax, and final amount. With tax enabled, wait for address verification and the tax calculation.',
      'Check a selected nexus state and an unselected state without paying. Separate mode should add applicable tax only where configured. Included mode should show the disclosure and keep applicable tax inside the quoted tax-inclusive amount.',
      'Try the narrow phone layout. Make sure the size selector, cart, address fields, and pay controls fit the screen and remain readable. Follow the contact link too.',
      'Only place a payment when you intend to create a real order or have a properly configured test environment. Do not enter test card numbers into live checkout. After an intentional test purchase, verify its payment and order record before treating the flow as proven.',
    ],
    example: ['Your expected order is a $40 print with a $5 flat shipping fee. Before tax, the amount should be $45. If the checkout shows $50, stop and check the quantity and shipping policy before changing random prices.'],
    check: ['The public product, cart, shipping, tax, and final total agree with your plan.', 'Any payment you intentionally made has the matching order and correct fulfillment information.'],
    troubleshoot: 'If a total is wrong, write down the product, option, quantity, address state, and displayed amounts. Check one setting at a time. If a payment result is unclear, check Orders and Stripe before trying to pay again.',
  },
  {
    slug: '18-manage-orders', title: 'Read an order and handle a customer question', group: '5. Sell and run the studio',
    summary: 'Find the purchased item, payment information, delivery address, and current status.',
    screen: 'orders.png', screenAlt: 'My order queue, shown with no studio work yet. Choose All orders & payments to review purchases.',
    tool: { label: 'Open all orders', href: '/admin/orders?view=all' },
    before: 'Have the order number or the buyer’s email ready. Order status, payment status, and shipping progress describe different parts of the work. Read the order before changing a status.',
    steps: [
      'Open Orders. Use the all-orders view to see purchases, then use status filters to narrow the list. If you are in My order queue, choose All orders & payments to review the full sale.',
      'Open the matching order. Compare the buyer, items, sizes, quantities, and date. Two similar titles may be different sizes, so check the option details rather than only the artwork name.',
      'Read the order summary. Separate merchandise, shipping, discounts, and tax when reviewing the total. Included tax is part of the amount already paid; separate tax is added to the taxable amount.',
      'Confirm the payment information before producing or shipping. If payment is failed, pending, or disputed, resolve that issue using the payment record and your business process. An abandoned cart is not a paid order.',
      'Review the saved shipping address and fulfillment method. The order keeps the choice made for that purchase. Today’s Use Lumaprints setting does not prove how this earlier order should be made.',
      'Answer the customer using the order’s facts: what was purchased, whether production has begun, and any available tracking. Keep private details in your normal customer service channel rather than public page content.',
      'If a refund or cancellation is needed, check both payment and production. A status label alone is not proof that money was refunded or a printer stopped work. Verify the actual payment refund and provider outcome separately.',
    ],
    example: ['A buyer asks where the 12 × 16 print is. Open their order, confirm that exact size, and check whether it is in production or shipped. If shipped, use its tracking link. Do not guess a delivery date from the order date alone.'],
    check: ['You found the correct paid order and its saved fulfillment path.', 'Your customer reply matches the production and tracking facts shown.'],
    troubleshoot: 'If you cannot find the order, remove status filters and check the date and email. If a buyer says they paid but no order appears, inspect the payment reference before asking them to pay again.',
  },
  {
    slug: '19-fulfill-and-track-orders', title: 'Make, pack, ship, and track an order', group: '5. Sell and run the studio',
    summary: 'Move studio work through its stages and keep shipment records tied to the purchased item.',
    screen: 'order-detail.png', screenAlt: 'Shipped stage in the studio queue; no shipped work yet.',
    tool: { label: 'Open the fulfillment queue', href: '/admin/orders' },
    before: 'Confirm payment and read the purchased size, material, quantity, and address. Check whether this order belongs to your studio or the print provider. Work from the order’s saved details, not a product you may have edited later.',
    steps: [
      'Open the studio queue or order detail. For studio work, read the work item and its Stage. Assign the work and review the Promised ship date so you know what needs attention first.',
      'For a print, use Open purchased production file when shown. That file belongs to the purchased specifications. Compare the output with the saved size, material, frame, and other details before making the item.',
      'Update Stage as work moves through printing, framing, and packing where those stages apply. For an original, focus on preparing and packing the existing piece. Choose Save work progress to keep your changes.',
      'If something blocks progress, use On hold and give a clear Hold reason. Write useful internal notes, such as a damaged frame or an address question. Do not mark an item shipped just to move it out of the queue.',
      'After handing the package to the carrier, open Record a shipment. Enter the quantity from each work item in this package, Carrier, and Tracking number. Add a tracking URL or postage cost if needed. Choose Save shipment & notify customer. A carrier, tracking number, and at least one item quantity are required. Record partial shipments separately.',
      'For items shown in Shipping & Tracking, enter Carrier, Tracking number, and the optional Tracking URL. Save tracking, then use Mark shipped only after the carrier has the package. Mark delivered after delivery is confirmed.',
      'For Lumaprints work, check the provider’s actual production and shipping progress. Do not also make the same order in your studio unless you have confirmed the provider will not fulfill it.',
    ],
    example: ['An order has two prints but only one is ready. Pack and record the ready print with its quantity and tracking. Keep the second print in its real work stage. One shipped package does not mean both items were shipped.'],
    check: ['The recorded shipment matches the real package and quantity.', 'The tracking link opens the carrier’s page, and unfinished work still appears as unfinished.'],
    troubleshoot: 'If a production file is unavailable or an address needs review, put the work on hold and resolve it before printing or buying postage. If tracking is wrong, correct the record; do not create a second physical shipment by accident.',
  },
  {
    slug: '20-daily-business-routine', title: 'Read your dashboard and run your daily routine', group: '5. Sell and run the studio',
    summary: 'Understand your sales totals, review tax by state, and turn the numbers into today’s next steps.',
    screen: 'sales-dashboard.png', screenAlt: 'Example sales tax tracker on the main Dashboard, using sample orders. Your live totals will differ.',
    tool: { label: 'Open your dashboard', href: '/admin' },
    relatedTools: [{ label: 'Jump to sales tax by state', href: '/admin#sales-tax' }],
    before: 'Keep your order and payment records nearby. Sales money is not the same as profit: some money pays for tax, shipping, production, and other expenses. The dashboard uses saved live paid orders. Test orders and records with an unknown payment mode are excluded and reported for review.',
    steps: [
      'Open Dashboard in the admin menu. Under Reporting period, choose Last 30 days, Last 90 days, This quarter, Last 365 days, or This year. Read the displayed start and end dates. The report groups orders by their created date in America/Chicago time, including today.',
      'Read the four sales cards. Paid orders counts the orders included in this report. Recorded order totals adds the recorded amounts, including shipping and tax, before refunds. Recorded sales before tax subtracts known tax from those totals; it still includes shipping and is before refunds. Average order total divides the recorded total by the number of paid orders.',
      'Read Full refunds recorded and Order totals after those full refunds. They use the orders’ current recorded full-refund status. Partial refunds, payment fees, disputes, production costs, and state tax payments are not automatically subtracted from these figures. Recorded sales before tax is not a profit number.',
      'Open Recent orders in this period. It shows the latest 25 paid live orders in your selected period. Choose an order number to inspect that purchase. Use View all orders for the full order list. Give each open order a clear next action, such as packing, checking payment, or answering a customer.',
      'Find Sales tax tracker and Tax by state. Add Included tax and Added tax to understand Recorded tax. Subtract Full-refund tax to get Net recorded tax. Read Review and the warnings. Missing tax information, partial refunds, and unknown records need attention before filing. An empty report or $0 recorded tax does not prove you owe no tax.',
      'Check customer questions, work due soon, and tracking problems. Review sold originals and print availability. Keep options live only when you can make them. Use the order’s saved specifications when preparing work; today’s product edits do not rewrite what a customer purchased.',
      'Use Refresh report after a new order or recorded refund. Use Download CSV to save the state-tax summary and its date range. This download does not export the recent-order list. Keep it with your Stripe, refund, and state-payment records.',
      'Once a week, compare prices with current costs using guides 9 through 11. Make one small improvement, such as clearer product wording or a better photo. Follow the filing schedule from each state and keep payments to the state in your own records; the dashboard does not track those payments.',
    ],
    example: [
      'Two-order example, using the illustrative tax amounts from guide 12: Order A totals $108.25, including $8.25 added tax. Order B totals $100, including $7.62 tax within its price. Paid orders is 2. Recorded order totals is $108.25 + $100 = $208.25.',
      'Add the taxes: $8.25 + $7.62 = $15.87. Subtract tax from the recorded totals: $208.25 − $15.87 = $192.38 Recorded sales before tax. Find the average: $208.25 ÷ 2 = $104.125, rounded to $104.13. These are sales figures before refunds and expenses, not take-home profit.',
      'If all $108.25 of Order A is later refunded and recorded, Full refunds recorded is $108.25. Subtract it from $208.25 to get $100 in Order totals after those full refunds. The four sales cards still describe the original orders before refunds. The remaining $100 still contains tax and must also cover costs and fees; it is not $100 of profit.',
    ],
    extra: [{ title: 'Find designs, features, and communication', paragraphs: ['For homepage designs, open Pages → Design Assets and find Homepage designs. For funnel designs, use Sales funnels on the same page. These design choices live together there; use the regular Pages editor when you only need to change a sentence.', 'To review the feature list, open Settings and expand Features built. For project conversations and notes, scroll to the communication area near the bottom of Dashboard. Sales, tax, fulfillment, and quick links remain easy to reach above it.'] }, { title: 'Know what your date choice means', paragraphs: ['An order created in September belongs to a September date range even if a refund is recorded in October. Because the report reads the refund status known now, that later refund can change the September group of orders. This is a review of selected orders, not a list of every tax transaction that happened during a filing period.', 'If Recorded sales before tax says Needs review, an included order lacks a reliable tax amount. Check the warnings and compare the actual order and payment records. Do not replace an unknown amount with zero just to make the report look complete.'] }],
    check: ['The displayed dates match the orders you meant to review.', 'You can explain the difference between total payments, sales before tax, net recorded tax, and profit.', 'Every open order has a next action, and you have reviewed missing-data and refund warnings.'],
    troubleshoot: 'If an order is missing, check the date range, payment status, and live versus test mode. Use View all orders and compare Stripe when a payment is unclear. If a report cannot load, use Try again; do not treat an error as a zero total. Review state payments separately when working out what remains to pay.',
  },
]

export function getHelpArticle(slug: string) {
  return helpArticles.find((article) => article.slug === slug)
}
